
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */

#include "AIRMapMarkerManagerTurboModule.h"

using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_AIRMapMarkerManagerTurboModule_showCallout(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args, size_t count){
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "showCallout", args, count);
}

static jsi::Value __hostFunction_AIRMapMarkerManagerTurboModule_hideCallout(jsi::Runtime &rt, react::TurboModule &turboModule,
                                                           const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "hideCallout", args, count);
}

static jsi::Value __hostFunction_AIRMapMarkerManagerTurboModule_redrawCallout(jsi::Runtime &rt, react::TurboModule &turboModule,
                                                                    const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "redrawCallout", args, count);
}

static jsi::Value __hostFunction_AIRMapMarkerManagerTurboModule_animateMarkerToCoordinate(jsi::Runtime &rt,
                                                                              react::TurboModule &turboModule,
                                                                              const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "animateMarkerToCoordinate", args, count);
}

static jsi::Value __hostFunction_AIRMapMarkerManagerTurboModule_redraw(
    jsi::Runtime &rt, react::TurboModule &turboModule, const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "redraw", args, count);
}

AIRMapMarkerManagerTurboModule::AIRMapMarkerManagerTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
    : ArkTSTurboModule(ctx, name) {
    methodMap_["showCallout"] = MethodMetadata{0, __hostFunction_AIRMapMarkerManagerTurboModule_showCallout};
    methodMap_["hideCallout"] = MethodMetadata{0, __hostFunction_AIRMapMarkerManagerTurboModule_hideCallout};
    methodMap_["redrawCallout"] = MethodMetadata{0, __hostFunction_AIRMapMarkerManagerTurboModule_redrawCallout};
    methodMap_["animateMarkerToCoordinate"] = MethodMetadata{2, __hostFunction_AIRMapMarkerManagerTurboModule_animateMarkerToCoordinate};
    methodMap_["redraw"] = MethodMetadata{0, __hostFunction_AIRMapMarkerManagerTurboModule_redraw};
}