
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include "ShadowNodes.h"
#include <react/renderer/core/ConcreteComponentDescriptor.h>

namespace facebook {
namespace react {

    using AIRMapComponentDescriptor = ConcreteComponentDescriptor<AIRMapShadowNode>;
    using AIRMapMarkerComponentDescriptor = ConcreteComponentDescriptor<AIRMapMarkerShadowNode>;
    using AIRMapPolylineComponentDescriptor = ConcreteComponentDescriptor<AIRMapPolylineShadowNode>;
    using AIRMapPolygonComponentDescriptor = ConcreteComponentDescriptor<AIRMapPolygonShadowNode>;
    using AIRMapCircleComponentDescriptor = ConcreteComponentDescriptor<AIRMapCircleShadowNode>;
    using AIRMapCalloutComponentDescriptor = ConcreteComponentDescriptor<AIRMapCalloutShadowNode>;
    using AIRMapCalloutSubviewComponentDescriptor = ConcreteComponentDescriptor<AIRMapCalloutSubviewShadowNode>;
    using GeojsonComponentDescriptor = ConcreteComponentDescriptor<GeojsonShadowNode>;
    using AIRMapUrlTileComponentDescriptor = ConcreteComponentDescriptor<AIRMapUrlTileShadowNode>;
    using AIRMapWMSTileComponentDescriptor = ConcreteComponentDescriptor<AIRMapWMSTileShadowNode>;
    using AIRMapOverlayComponentDescriptor = ConcreteComponentDescriptor<AIRMapOverlayShadowNode>;

} // namespace react
} // namespace facebook
