
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */

#include "MapsTurboModule.h"

using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_MapsTurboModule_getCamera(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args, size_t count){
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "getCamera", args, count);
}

static jsi::Value __hostFunction_MapsTurboModule_setCamera(jsi::Runtime &rt, react::TurboModule &turboModule,
                                                           const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "setCamera", args, count);
}

MapsTurboModule::MapsTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
    : ArkTSTurboModule(ctx, name) {
    methodMap_["getCamera"] = MethodMetadata{0, __hostFunction_MapsTurboModule_getCamera};
    methodMap_["setCamera"] = MethodMetadata{1, __hostFunction_MapsTurboModule_setCamera};
}