
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include "States.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char AIRMapComponentName[];

JSI_EXPORT extern const char AIRMapMarkerComponentName[];

JSI_EXPORT extern const char AIRMapPolylineComponentName[];

JSI_EXPORT extern const char AIRMapPolygonComponentName[];

JSI_EXPORT extern const char AIRMapCircleComponentName[];

JSI_EXPORT extern const char AIRMapCalloutComponentName[];

JSI_EXPORT extern const char AIRMapCalloutSubviewComponentName[];

JSI_EXPORT extern const char GeojsonComponentName[];

JSI_EXPORT extern const char AIRMapUrlTileComponentName[];

JSI_EXPORT extern const char AIRMapWMSTileComponentName[];

JSI_EXPORT extern const char AIRMapOverlayComponentName[];

/*
 * `ShadowNode` for <AIRMap> component.
 */
using AIRMapShadowNode = ConcreteViewShadowNode<AIRMapComponentName, AIRMapProps, AIRMapEventEmitter, AIRMapState>;

using AIRMapMarkerShadowNode = ConcreteViewShadowNode<AIRMapMarkerComponentName, AIRMapMarkerProps, AIRMapMarkerEventEmitter, AIRMapMarkerState>;

using AIRMapPolylineShadowNode = ConcreteViewShadowNode<AIRMapPolylineComponentName, AIRMapPolylineProps, AIRMapPolylineEventEmitter, AIRMapPolylineState>;

using AIRMapPolygonShadowNode = ConcreteViewShadowNode<AIRMapPolygonComponentName, AIRMapPolygonProps, AIRMapPolygonEventEmitter, AIRMapPolygonState>;

using AIRMapCircleShadowNode = ConcreteViewShadowNode<AIRMapCircleComponentName, AIRMapCircleProps, AIRMapCircleEventEmitter, AIRMapCircleState>;

using AIRMapCalloutShadowNode = ConcreteViewShadowNode<AIRMapCalloutComponentName, AIRMapCalloutProps, AIRMapCalloutEventEmitter, AIRMapCalloutState>;

using AIRMapCalloutSubviewShadowNode = ConcreteViewShadowNode<AIRMapCalloutSubviewComponentName, AIRMapCalloutSubviewProps,
                                                       AIRMapCalloutSubviewEventEmitter, AIRMapCalloutSubviewState>;

using GeojsonShadowNode =ConcreteViewShadowNode<GeojsonComponentName, GeojsonProps, GeojsonEventEmitter, GeojsonState>;

using AIRMapUrlTileShadowNode = ConcreteViewShadowNode<AIRMapUrlTileComponentName, AIRMapUrlTileProps, AIRMapUrlTileEventEmitter, AIRMapUrlTileState>;

using AIRMapWMSTileShadowNode = ConcreteViewShadowNode<AIRMapWMSTileComponentName, AIRMapWMSTileProps, AIRMapWMSTileEventEmitter, AIRMapWMSTileState>;

using AIRMapOverlayShadowNode = ConcreteViewShadowNode<AIRMapOverlayComponentName, AIRMapOverlayProps, AIRMapOverlayEventEmitter, AIRMapOverlayState>;

} // namespace react
} // namespace facebook
