
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include "ShadowNodes.h"

namespace facebook {
namespace react {

    extern const char AIRMapComponentName[] = "AIRMap";

    extern const char AIRMapMarkerComponentName[] = "AIRMapMarker";

    extern const char AIRMapPolylineComponentName[] = "AIRMapPolyline";

    extern const char AIRMapPolygonComponentName[] = "AIRMapPolygon";

    extern const char AIRMapCircleComponentName[] = "AIRMapCircle";

    extern const char AIRMapCalloutComponentName[] = "AIRMapCallout";

    extern const char AIRMapCalloutSubviewComponentName[] = "AIRMapCalloutSubview";

    extern const char GeojsonComponentName[] = "Geojson";

    extern const char AIRMapUrlTileComponentName[] = "AIRMapUrlTile";

    extern const char AIRMapWMSTileComponentName[] = "AIRMapWMSTile";

    extern const char AIRMapOverlayComponentName[] = "AIRMapOverlay";

    } // namespace react
} // namespace facebook
