/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

namespace facebook {
namespace react {

class AIRMapState {
public:
    AIRMapState() = default;
};

class AIRMapMarkerState {
  public:
      AIRMapMarkerState() = default;
};

class AIRMapPolylineState {
  public:
      AIRMapPolylineState() = default;
};

class AIRMapPolygonState {
  public:
      AIRMapPolygonState() = default;
};

class AIRMapCircleState {
  public:
      AIRMapCircleState() = default;
};

class AIRMapCalloutState {
  public:
      AIRMapCalloutState() = default;
};

class AIRMapCalloutSubviewState {
  public:
      AIRMapCalloutSubviewState() = default;
};

class GeojsonState {
  public:
      GeojsonState() = default;
};

class AIRMapUrlTileState {
  public:
      AIRMapUrlTileState() = default;
};

class AIRMapWMSTileState {
  public:
      AIRMapWMSTileState() = default;
};

class AIRMapOverlayState {
  public:
      AIRMapOverlayState() = default;
};

} // namespace react
} // namespace facebook