/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ColorPropConverter;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;

public class RNMapsCircleManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & RNMapsCircleManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public RNMapsCircleManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "center":
        mViewManager.setCenter(view, (ReadableMap) value);
        break;
      case "fillColor":
        mViewManager.setFillColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "radius":
        mViewManager.setRadius(view, value == null ? Double.NaN : ((Double) value).doubleValue());
        break;
      case "strokeColor":
        mViewManager.setStrokeColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "strokeWidth":
        mViewManager.setStrokeWidth(view, value == null ? 1f : ((Double) value).floatValue());
        break;
      case "tappable":
        mViewManager.setTappable(view, value == null ? false : (boolean) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
