/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;

public interface RNMapsCalloutManagerInterface<T extends View> {
  void setAlphaHitTest(T view, boolean value);
  void setTooltip(T view, boolean value);
}
