export { default as AIRMapCallout } from './AIRMapCallout';
export { default as AIRMapCalloutSubview } from './AIRMapCalloutSubview';
export { default as AIRMapCircle } from './AIRMapCircle';
export { default as AIRMapLite } from './AIRMapLite';
export { default as AIRMap } from './AIRMapLite';
// export { default as AIRMapLocalTile } from './AIRMapLocalTile';
export { default as AIRMapMarker } from './AIRMapMarker';
export { default as AIRMapOverlay } from './AIRMapOverlay';
export { default as AIRMapPolygon } from './AIRMapPolygon';
export { default as AIRMapPolyline } from './AIRMapPolyline';
// export { default as AIRMapUrlTile } from './AIRMapUrlTile';
// export { default as AIRMapWMSTile } from './AIRMapWMSTile';
